### ISSUE TITLE
Syntax Highlighter breaks if multiple blocks have the same color

### ISSUE THREAD

**Issue by shysaur** [shysaur/Fragaria#2]
The syntax highlighter reads in various places on the existing coloring to:
- check if a string parsing operation was suspended (range too short)
- check if a string is inside a comment
- possibly other places?

**Comment by balthisar** [comment]
A hacky way to do it while observing the user defaults would be to ensure that all colors are unique, even if the defaults specify the same color for multiple text types. For example, change the R value by one bit, or brightness, or something not really noticeable.

**Comment by shysaur** [comment]
Now you have the issue of tracking which bits you add, otherwise we'll end up creating duplicates of the manipulated color.

**Comment by balthisar** [comment]
Do you have sample text that causes this failure?

**Comment by shysaur** [comment]
I'm already looking into it and added some infrastructure for fixing this in defe94c.

Any text will do, the problem is that some syntax coloring passes look at the color added in previous passes. The issue is that if some passes assign the same color, this code will get confused and will probably produce incorrect results. The passes which do this are mainly the ones that can do multiline coloring.

**Comment by shysaur** [comment]
Also, I assigned myself to this... :-)
