### ISSUE TITLE
Tri-state breakpoints; other breakpoint images/colors

### ISSUE THREAD

**Issue by balthisar** [shysaur/Fragaria#22]
Raising this as a proposed issue/feature request.

Right now the breakpoints are dead-simple, and that's a good thing. If we want to make it more complicated, though, there are opportunities for multiple colors and/or image sources (mentioned in another issue, but thought it deserved to be top-level).

There is also the possibility of tri-state (or multi-state) breakpoints, e.g., breakpoint enabled, breakpoint disabled, and no breakpoint, a la Xcode.

For discussion I would propose that it's silly for a view to manage all of this, and would propose that the application is responsible. This would leave the breakpoint as a decoration only (with click feedback), but would have to provide some mechanism to provide different breakpoint images.

**Comment by shysaur** [comment]
The application is already responsible for breakpoints. We don't even store them anywhere, the breakpoint delegate does that.

The "fix" for this issue would be adding a breakpoint delegate method for returning some styling information (or an NSImage to draw). It should be an easy task.

**Comment by balthisar** [comment]
Yes, just raising it as an issue because this seems to be better than the TODO file.

**Comment by balthisar** [comment]
The old breakpoint images are still in the repo. I thought they got cleared out in an earlier PR, but either I didn't do that, or they snuck back in during a merge.

I won't raise a PR just for this, but I'll include it if I finally solve the preferences problem I've been banging my head over.

**Comment by shysaur** [comment]
Woops, wrong issue number!

**Comment by shysaur** [comment]
Now the breakpoint delegate can specify the color of each breakpoint, and it should be sufficient for 99% of the applications (I hope – there's always been very little variety on the design of breakpoints markers).

**Comment by balthisar** [comment]
:+1:
