### ISSUE TITLE
MGSFragariaPreferences role?

### ISSUE THREAD

**Issue by balthisar** [shysaur/Fragaria#30]
MGSFragariaPreferences is currently instituted as a singleton, but the only use of it in the code is in the Simple demo application, where it's only used to eventually resolve back to the shared NSUserDefaultsController.

It also provides ready-made instances of the two view controllers, but the demo app is instantiating its own controllers, so these aren't really necessary, either, unless we want them to remain for other applications to use.

I'll keep it all in and add lazy instantiation for the controllers, but I'd like to rip this out entirely, as I don't see a need for it.

**Comment by shysaur** [comment]
First we have to move out its initializeValues method and the preference constants to the new preferences controller. Then we can delete it.

**Comment by shysaur** [comment]
Now the files for MGSFragariaPreferences are just the declarations for the preference keys.
