### ISSUE TITLE
Some behavior too dependent on NSUserDefaults

### ISSUE THREAD

**Issue by balthisar** [shysaur/Fragaria#6]
A lot of Smultron's and Fragaria's settings and behaviors are linked directly to NSUserDefaults, meaning that multiple instances of Fragaria can't have independent settings, or the custom setting is undone whenever the default changes.

This is something I plan to tackle, but I'm not sure if it's on your radar or not.

**Comment by shysaur** [comment]
Yes, I've seen this. I already improved on it when I remade the line number gutter: the gutter view itself doesn't even know of NSUserDefaults, and SMLLineNumbers was repurposed to observe for default changes and set the line number gutter's properties accordingly.

My idea was to make an exposed class (maybe named MGSDefaultsObserver) which registers as a KVO observer for Fragaria's preferences, and to replace all the explicit preference accesses with properties. The properties will then be controlled by this class, which can be subclassed by the app to provide custom behavior, or disabled entirely (by using an -automaticallyObservesDefaults:(BOOL) property on MGSFragaria). Then, when this will be done, SMLLineNumbers will go away (this new class will substitute for it).

As of today, for me it's not a priority. First, I'd like to kill the docSpec.

**Comment by shysaur** [comment]
Thinking again (and after trying to implement it) maybe the MGSDefaultsObserver approach is a bit too messy to handle.

**Comment by balthisar** [comment]
There's some dead code you accepted that I was planning to implement: MGSFragariaPreferencesController.

Rather than being an observer, it's intended to act as a warehouse for all of Fragaria's settings, but also work seamlessly with user defaults (or not), while not forcing the same properties onto all instances of Fragaria.

**Comment by shysaur** [comment]
Yeah yeah, I know I accepted it. But that dead code came with some other stuff I already planned to do (moving the examples and adding a documentation target), which made refusing it a bit more difficult in practice.

If you want to implement your stub, do it, by all means! But I'd have preferred to have plain old properties instead of a warehouse class.

**Comment by shysaur** [comment]
An alternative way to fix this is key-value bindings, that were invented just for this purpose.

**Comment by balthisar** [comment]
I've been struggling with this nearly full time the last few days, trying to build a solution that's nearly transparent. I'm close, and it depends a lot on bindings.

However my thoughts are these now:
- It's the responsibility of the enclosing app to deal with user defaults, not Fragaria's per se.
- I'd strip all of the internal calls to NSUserDefaults current UserDefaults (and Smultron's macro, etc), and use properties instead.
- At Fragaria's instantiation (only) we can let it peek at defaults, or the containing app can pass it a dictionary, or simply set all of the properties.
- I'd move the user defaults user interface into a new Framework, and provide a utility or two to make the previous point easier.
- The new Framework could actually bind against a Fragaria instance and use KVO/KVC to automate things.

I understand the current docSpec and use of defaults "gets around" a lot of object ownership issues, but as you said in another issue, I don't think that's a concern in modern Objective-C.

The above, conceptually, would give us a Fragaria framework that's completely independent of user defaults, and another framework that can integrate user defaults if desired.

Any thoughts?

**Comment by shysaur** [comment]
What you described is basically how the whole Cocoa world works, so it looks the right thing to do.

At instantiation the Cocoa way would be to provide decent defaults (not read from the user defaults) and then the instantiatior has to set all the properties.

**Comment by balthisar** [comment]
:) I wasted days trying to tackle this before coming to the conclusion that it's not practical while the docSpec is hiding properties.

**Comment by balthisar** [comment]
Now I'm ready to dedicate some time to a replacement preferences controller / observer.

Currently the MGSTemporaryPreferencesObserver maintains the historical behavior of Fragaria, which means that in a single application it's still not possible to use separate properties on multiple instances (which is a use case I happen to have a need for).

Given that the host application should be responsible for managing properties and preferences, I think that this is a good opportunity for a separate framework within the project. My initial goals are:
- It can be used optionally.
- It will not attempt to reproduce the current behaviour of MGSTemporaryPreferencesObserver.
- It will manage multiple sets of defaults allowing multiple instances of Fragaria.
- There will be a mechanism for some defaults to be "shared" or "master" within a single application.
- I will convert the current windows and controllers into views and controllers to allow more flexibility.
- Possibly provide a couple of windows/controllers using the new views to make them simple to implement.
- Add color themes.
- In any case these UI will have to be modified significantly to work with multiples sets of userDefaultsKeys.

This leads to the question, what do we do with the current defaults system and observer? Some thoughts:
- Keep it.
  - Rename it.
  - Clean it up a bit.
  - New MGSFragaria designated initializer: `initWithView:useLegacyDefaults:`
- Eliminate it completely.
  - We've been logging warnings for a few days. Perhaps it's not enough notice.
  - The network graph doesn't indicate any more forks, so maybe existing base isn't a concern.

**Comment by shysaur** [comment]
I'd keep MGSTemporaryPreferencesObserver until your new system is done; then, when your are done with the new stuff, it will be easier to decide if the old stuff has still  some value.

**Comment by balthisar** [comment]
This can probably be closed.

**Comment by shysaur** [comment]
Right!
