### ISSUE TITLE
Remove docSpecs

### ISSUE THREAD

**Issue by shysaur** [shysaur/Fragaria#7]
Originally, docSpecs were used to persist document state. But there are far less painful alternatives.
- Under ARC, usage of docSpecs basically create a circular retain cycle on all of Fragaria's internal objects, which can be solved only by sprinkling __weaks all around, and that's not good by definition.
- DocSpecs makes even interacting with other objects a pain: every time you have to get an object you have to make call objectForKey:MGSVeryLongAndSpammyConstant or valueForKey:MGSVeryLongAndSpammyConstant.
- They are exposed, and thus their original _raison d'etre_ has vanished.
- DocSpecs flatten the entire object graph. This would be enough of a reason by itself to get rid of them.

The ideal "replacement" is to analyze the current object dependencies and then to make explicit ivars for object references. Then, the existence of docSpecs can be simulated (for backcompat purposes) by reimplementing objectForKey: and setObject:forKey: and the docSpec accessor in MGSFragaria. setDocSpec: should be reimplemented to log out an error, since I don't think anybody actually used it.

Also, the header for MGSFragaria exposes a lot of stuff about the creation of docSpecs and some stuff for accessing the content of a docSpec to make up for docSpecs being NSMutableDictionaries instead of custom objects. This stuff has to be removed (or stubbed out) as well, maybe in a MGSBackcompat category.

**Comment by balthisar** [comment]
:+1: 

> This stuff has to be removed (or stubbed out) as well, maybe in a MGSBackcompat category.

Or rename the project and leave backwards compatibility behind.

**Comment by balthisar** [comment]
This seems like the right issue to post this under. As part of the elimination of the docspec and moving to iVars (or properties?) it might also be an excellent time to move to adopting them through protocols.

This is somewhat inspired by your changing from the old ruler to Noodlekit's: If we have an ivar for the ruler and a protocol for it, then we don't have to subclass the ruler if someone wants to swap in another. Similar for the textview not having to descend from SMLTextView.

It's a big task and necessitates taking a full inventory of what is interacting and where. You're about 20 steps ahead of me in that with all of the refactoring you've been doing.

**Comment by balthisar** [comment]
I think this is the number one priority for structural development. I tried to remove a simple property from the docSpoc (`syntaxDefinitionName`) so that I could start working on the new preferences controller, and it was frustrating (git stash \ git stash drop; I gave up).

It's still certainly possible to work in some of the other issues with the current docSpec, but I don't see a practical way to _cleanly_ overhaul some of the other major structural elements (like user defaults) until this monstrosity it killed.

Given the updated readme about backward compatibility, can I assume you won't care about a backwards compatible solution to this? I think I can slay this beast, but it's going to require a lot of carving.

**Comment by shysaur** [comment]
The only thing I want to keep around are objectForKey: and setObject:forKey: in MGSFragaria, because they were the recommended (or only) way of doing things, and every user of Fragaria is using these methods.

**Comment by balthisar** [comment]
Once everything is property-based, they will be redundant with setValue:forKey and valueForKey. I might think about a deprecation warning when the time comes.

**Comment by shysaur** [comment]
Right.

**Comment by shysaur** [comment]
Fixed by 9e0563f.
