### ISSUE TITLE
Color well enabling does not work if the associated "coloursX" property is on global scope

### ISSUE THREAD

**Issue by shysaur** [shysaur/Fragaria#75]
In the current MGSFragariaViewModern example, the Attributes color well is an example of this misbehavior.

**Comment by balthisar** [comment]
I have a beautiful fix, but I broke something else that I'm trying to resolve before PR'ing it.

**Comment by shysaur** [comment]
OK, it was just to see if you were aware of this.

**Comment by balthisar** [comment]
If you have time, take a look at 9184fd8fb5c5265f19815ce36335314dc3fd2750. It's a WIP and I don't want to PR broken code, but it makes the panels work a lot more nicely, auto-hides a lot of disable stuff, and deals well with the color schemes if not all of the properties are available. Oh, and also make all of the scheme files human-readable/editable.

The last thing I'm struggling with is getting MGSColourSchemesController to run its `setup` only after the NSObjectController is connected to its data. It's 11:00 pm here and I'm tired and frustrated, and I'll have a fresh look at it tomorrow, but at least you'll have a chance to see the direction its going in.

It's a WIP branch and so not nicely segregated, but some of the earlier commits are safe to pull in if you want them -- spacing, first responder stuff -- through 12f626a4b477575e357f2fcce647d313bb2c1278 should be pretty safe.

If you don't pull them, I'll clean clean up the WIP branch before the PR and get them then.
