### ISSUE TITLE
MGSSyntaxController get file extension based on a given name.

### ISSUE THREAD

**Issue by softmastx** [shysaur/Fragaria#95]
How to get a file extension when user selected language combobox (MGSSyntaxController) ?

Thanks

**Comment by shysaur** [comment]
Currently there isn't any method on MGSSyntaxController to do this, but you could try to manually parse SyntaxDefinitions.plist (the file extensions used by Fragaria are in there).

**Comment by softmastx** [comment]
Thank you for the info.
